---
- name: install nginx
  yum: name=nginx state=present
  notify:
    - start nginx

        
- name: bootstrap config
  template: src=templates/default-site.j2 dest=/etc/nginx/conf.d/default.conf
  with_items:
    - { src: "templates/default-site.j2" , dest: "/etc/nginx/conf.d/default.conf"}
    - { src: "templates/nginx.conf.j2" , dest: "/etc/nginx/nginx.conf"}
  notify: restart nginx 
