---

- hosts: all
  sudo: true
  gather_facts: no
  remote_user: vagrant

  tasks:

    - name : Add ssh key
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
