- hosts: all
  vars:
    - allips: |
                    {% set comma = joiner(",") %}
                    {% for host in groups['mygroup'] -%}
                      {{ comma() }}{{ hostvars[host]['ansible_eth0']['ipv4']['address']}}
                    {%- endfor -%}
